Repository gta-reversed/gta-reversed, pull requests merged in 2022-01, with the labels that each got.

#12 CMirrors
  source/InjectHooksMain.cpp
  source/game_sa/Camera.cpp
  source/game_sa/Core/Vector.cpp
  source/game_sa/Core/Vector.h
  source/game_sa/Core/Vector2D.h
  source/game_sa/CustomCarEnvMapPipeline.cpp
  source/game_sa/Fx/CarFXRenderer.cpp
  source/game_sa/Mirrors.cpp
  source/game_sa/Mirrors.h
  source/game_sa/PlantMgr.cpp
  source/game_sa/PostEffects.cpp
  source/game_sa/PostEffects.h
  source/game_sa/common.cpp
  source/game_sa/common.h
Labels: invalid

#33 CSkidmarks
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/Camera.h
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Game.cpp
  source/game_sa/Skidmark.cpp
  source/game_sa/Skidmark.h
  source/game_sa/Skidmarks.cpp
  source/game_sa/Skidmarks.h
  source/game_sa/SurfaceInfos_c.h
Labels: invalid

#150 CWindModifiers
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/Collision/Collision.h
  source/game_sa/Entity/Entity.cpp
  source/game_sa/WindModifiers.cpp
  source/game_sa/WindModifiers.h
Labels: help wanted, untested

#146 CPedPlacement
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/PedPlacement.cpp
  source/game_sa/PedPlacement.h
  source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillTimed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexUseSwatRope.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleGetUp.cpp
Labels: help wanted, untested

#145 Suppress unnecessary warnings
  CMakeLists.txt
  premake5.lua
Labels: enhancement

#151 CUpsideDownCarCheck
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/Scripts/TheScripts.cpp
  source/game_sa/UpsideDownCarCheck.cpp
  source/game_sa/UpsideDownCarCheck.h
Labels: help wanted, untested
