Repository gta-reversed/gta-reversed, pull requests merged in 2022-08, with the labels that each got.

#7 Reverse 29 CHud funcs
  source/game_sa/Enums/eHud.h
  source/game_sa/Hud.cpp
  source/game_sa/Hud.h
  source/game_sa/Messages.h
  source/game_sa/Sprite2d.cpp
  source/game_sa/Timer.h
  source/game_sa/common.h
Labels: help wanted

#255 CTaskSimpleSlideToCoord
  source/InjectHooksMain.cpp
  source/game_sa/Core/Vector.h
  source/game_sa/Pools.h
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterAnyCarAsDriver.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleAnim.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunNamedAnim.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunNamedAnim.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSlideToCoord.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSlideToCoord.h
  source/reversiblehooks/ReversibleHooks.h
Labels: untested

#329 `CTaskSimpleCarWaitToSlowDown`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitToSlowDown.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitToSlowDown.h
Labels: untested

#336 `NOTSA_UNREACHABLE`: Pop-up message box like assert instead of printing to `std::cout`
  source/Base.h
  source/reversiblehooks/ReversibleHooks.cpp
Labels: tested

#334 Fix CCollisionEventScanner definition
  source/game_sa/Collision/CollisionEventScanner.cpp
  source/game_sa/Collision/CollisionEventScanner.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/PedIntelligence.cpp
  source/game_sa/PedIntelligence.h
Labels: tested

#358 `CTaskComplexFleePoint`
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/Animation/AnimManager.cpp
  source/game_sa/Core/Vector2D.h
  source/game_sa/Enums/eMeleeCombo.h
  source/game_sa/Models/BaseModelInfo.h
  source/game_sa/Tasks/TaskComplexSequence.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexFleePoint.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexFleePoint.h
  source/game_sa/Tasks/TaskTypes/TaskComplexLeaveAnyCar.h
  source/game_sa/WeaponInfo.cpp
  source/game_sa/WeaponInfo.h
Labels: untested

#357 `CTaskSimpleWaitUntilAreaCodesMatch`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleWaitUntilAreaCodesMatch.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleWaitUntilAreaCodesMatch.h
Labels: untested

#356 `CTaskSimpleWaitUntilPedIsInCar`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleWaitUntilPedIsInCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleWaitUntilPedIsInCar.h
Labels: untested

#349 `CTaskSimplePlayerOnFire`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTimer.h
  source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFire.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFire.h
Labels: untested

#348 `CTaskSimpleSay`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSay.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSay.h
Labels: tested

#346 `CTaskSimpleRunTimedAnim`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunTimedAnim.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunTimedAnim.h
Labels: tested

#344 `CTaskSimpleLeaveGroup`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleLeaveGroup.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleLeaveGroup.h
Labels: tested

#340 `CTaskSimpleClearLookAt`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClearLookAt.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClearLookAt.h
Labels: untested

#335 `CTaskSimpleCarOpenDoorFromOutside`
  source/InjectHooksMain.cpp
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Gangs.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenDoorFromOutside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenDoorFromOutside.h
  source/game_sa/VehicleAnimGroupData.h
  source/reversiblehooks/ReversibleHooks.cpp
Labels: tested

#317 `CTaskSimpleCarAlign`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarAlign.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarAlign.h
  source/game_sa/VehicleAnimGroupData.cpp
Labels: tested

#311 `CTaskSimpleThrowControl`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleThrowControl.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleThrowControl.h
Labels: untested

#315 `CTaskSimpleBeKickedOnGround`
  source/InjectHooksMain.cpp
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleBeKickedOnGround.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleBeKickedOnGround.h
Labels: untested

#318 `CTaskSimpleCarCloseDoorFromInside`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/PlayerPed.cpp
  source/game_sa/Entity/Ped/PlayerPed.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromInside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromInside.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromOutside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromOutside.h
Labels: tested

#326 `CTaskSimpleCarJumpOut`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.h
Labels: tested

#331 `CTaskComplexLeaveBoat`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexLeaveBoat.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexLeaveBoat.h
Labels: untested

#332 `CTaskSimpleCarWaitForDoorNotToBeInUse`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitForDoorNotToBeInUse.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitForDoorNotToBeInUse.h
Labels: untested

#338 `CTaskSimpleCarSetTempAction`
  source/InjectHooksMain.cpp
  source/game_sa/AutoPilot.cpp
  source/game_sa/AutoPilot.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetTempAction.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetTempAction.h
Labels: untested

#339 `CTaskSimpleAffectSecondaryBehaviour`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskManager.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleAffectSecondaryBehaviour.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleAffectSecondaryBehaviour.h
Labels: untested

#341 `CTaskSimpleCower`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCower.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCower.h
Labels: untested

#323 CShopping
  source/game_sa/DamageManager.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Enums/eLevelName.h
  source/game_sa/Shopping.cpp
  source/game_sa/Shopping.h
Labels: tested

#325 Add MSVC Code Analysis
  .github/workflows/build.yml
Labels: tested

#396 Fix CRect field names
  source/game_sa/Camera.cpp
  source/game_sa/Core/QuadTreeNode.cpp
  source/game_sa/Core/QuadTreeNode.h
  source/game_sa/Core/Rect.cpp
  source/game_sa/Core/Rect.h
  source/game_sa/Entity/Entity.cpp
  source/game_sa/Entity/Physical.cpp
  source/game_sa/Font.cpp
  source/game_sa/Frontend/MenuManager_Draw.cpp
  source/game_sa/Hud.cpp
  source/game_sa/MenuSystem.cpp
  source/game_sa/Radar.cpp
  source/game_sa/Sprite2d.cpp
Labels: tested

#73 CGarages
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/Audio/entities/AEScriptAudioEntity.h
  source/game_sa/DamageManager.cpp
  source/game_sa/DamageManager.h
  source/game_sa/Entity/Object/Object.cpp
  source/game_sa/Entity/Object/Object.h
  source/game_sa/FileLoader.cpp
  source/game_sa/Game.cpp
  source/game_sa/GangWars.cpp
  source/game_sa/Garage.cpp
  source/game_sa/Garage.h
  source/game_sa/Garages.cpp
  source/game_sa/Garages.h
  source/game_sa/GenericGameStorage.cpp
  source/game_sa/GenericGameStorage.h
  source/game_sa/Hud.cpp
  source/game_sa/Pickups.cpp
  source/game_sa/TagManager.cpp
  source/game_sa/World.cpp
  source/game_sa/common.cpp
Labels: help wanted, untested

#387 `CTaskSimpleCarJumpOut`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleClearLookAt.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClearLookAt.h
Labels: tested

#384 `CTaskSimpleCarGetIn`
  source/InjectHooksMain.cpp
  source/game_sa/Enums/eTargetDoor.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetIn.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetIn.h
Labels: tested

#388 `CTaskSimpleCarCloseDoorFromInside `
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/PlayerPed.cpp
  source/game_sa/Entity/Ped/PlayerPed.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromInside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromInside.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromOutside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromOutside.h
Labels: tested

#367 `CTaskComplexInvestigateDeadPed` + stub for `CTaskComplexSignalAtPed`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStill.h
  source/game_sa/Tasks/TaskTypes/TaskComplexInvestigateDeadPed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexInvestigateDeadPed.h
  source/game_sa/Tasks/TaskTypes/TaskComplexSignalAtPed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexSignalAtPed.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.h
Labels: tested

#383 `CTaskSimpleCarOpenDoorFromOutside`
  source/InjectHooksMain.cpp
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Gangs.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenDoorFromOutside.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenDoorFromOutside.h
  source/game_sa/VehicleAnimGroupData.h
Labels: tested

#375 `CTaskSimpleSay`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTimer.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSay.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSay.h
Labels: tested

#377 `CTaskSimpleRunTimedAnim`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunTimedAnim.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunTimedAnim.h
Labels: tested

#390 `CTaskSimpleBikeJacked`
  source/InjectHooksMain.cpp
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Animation/AnimManager.h
  source/game_sa/Audio/entities/AEPedAudioEntity.h
  source/game_sa/Events/EventGroup.cpp
  source/game_sa/Events/EventGroup.h
  source/game_sa/General.cpp
  source/game_sa/General.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleBikeJacked.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleBikeJacked.h
  source/game_sa/common.cpp
  source/game_sa/common.h
Labels: tested

#368 Fix quadbike incorrect handling data used
  source/game_sa/Entity/Vehicle/Bike.cpp
  source/game_sa/Entity/Vehicle/QuadBike.cpp
  source/game_sa/Entity/Vehicle/QuadBike.h
  source/game_sa/RideAnimData.h
  source/game_sa/cHandlingDataMgr.h
Labels: tested

#400 Fix a security issue at CShopping::Buy
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Automobile.h
  source/game_sa/Shopping.cpp
Labels: tested

#373 `CTaskComplexOnFire`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Ped/Ped.cpp
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Events/EventHandler.cpp
  source/game_sa/Events/EventHandler.h
  source/game_sa/PedDamageResponse.h
  source/game_sa/Tasks/TaskTypes/TaskComplexOnFire.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexOnFire.h
Labels: tested

#366 Fix crash and resolve inlined function
  source/game_sa/World.cpp
  source/game_sa/World.h
Labels: tested

#406 `CTaskComplexSmartFleePoint`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexSmartFleePoint.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexSmartFleePoint.h
Labels: tested

#411 CBoat: Hook ctor/dtor and use virtual hooks for functions
  source/game_sa/Entity/Vehicle/Boat.cpp
  source/game_sa/Entity/Vehicle/Boat.h
Labels: tested

#414 Fix #409 + Move RenderScene to app.cpp
  source/app/app.cpp
  source/app/platform/win/win.cpp
  source/game_sa/Mirrors.cpp
Labels: tested

#413 Hook `CTaskComplexEnterCar`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.h
Labels: tested

#410 `CTaskComplexGoToBoatSteeringWheel`
  source/game_sa/Tasks/TaskTypes/TaskComplexGoToBoatSteeringWheel.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexGoToBoatSteeringWheel.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarDrive.cpp
Labels: tested

#401 `CTaskSimpleRunTimedAnim::StartAnim`: Fix callback not set
  source/game_sa/Tasks/TaskTypes/TaskSimpleRunTimedAnim.cpp
Labels: tested

#395 TaskComplexDestroyCar and derivatives
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCar.h
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarArmed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarArmed.h
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarMelee.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarMelee.h
  source/game_sa/Weapon.cpp
  source/game_sa/Weapon.h
Labels: tested

#398 `CustomPipeMaterialSetup`
  source/game_sa/Pipelines/CustomCarEnvMap/CustomCarEnvMapPipeline.cpp
Labels: tested

#376 `CTaskSimpleHandsUp`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleHandsUp.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleHandsUp.h
Labels: tested

#324 `CTaskSimpleCarGetOut`
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/game_sa/CarEnterExit.cpp
  source/game_sa/CarEnterExit.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetOut.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetOut.h
Labels: tested

#374 `CTaskSimplePlayerOnFire`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFire.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFire.h
Labels: tested

#386 `CTaskComplexLeaveBoat`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexLeaveBoat.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexLeaveBoat.h
Labels: tested

#369 CCarEnterExit
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Animation/AnimBlendSequence.cpp
  source/game_sa/Animation/AnimBlendSequence.h
  source/game_sa/CarEnterExit.cpp
  source/game_sa/CarEnterExit.h
  source/game_sa/Collision/ColModel.h
  source/game_sa/Entity/Entity.cpp
  source/game_sa/Entity/Entity.h
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Entity/Ped/PlayerPed.cpp
  source/game_sa/Entity/Ped/PlayerPed.h
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Enums/AnimationEnums.h
  source/game_sa/Enums/eCarNodes.h
  source/game_sa/Events/EventAcquaintancePed.cpp
  source/game_sa/GangWars.cpp
  source/game_sa/PedGroups.cpp
  source/game_sa/PedGroups.h
  source/game_sa/PedType.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedInAsDriver.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedInAsPassenger.h
  source/game_sa/UpsideDownCarCheck.cpp
  source/game_sa/UpsideDownCarCheck.h
  source/game_sa/World_Helper.cpp
Labels: tested

#362 `CTaskSimpleSitIdle`
  source/InjectHooksMain.cpp
  source/game_sa/General.cpp
  source/game_sa/General.h
  source/game_sa/Tasks/TaskTimer.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSitIdle.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSitIdle.h
Labels: tested

#391 `CTaskComplexTrackEntity`
  source/InjectHooksMain.cpp
  source/game_sa/Entity/Entity.cpp
  source/game_sa/Entity/Entity.h
  source/game_sa/Tasks/TaskTypes/TaskComplexTrackEntity.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexTrackEntity.h
Labels: untested

#361 `CTaskSimpleSitDown`
  source/InjectHooksMain.cpp
  source/game_sa/Animation/AnimBlendAssociation.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSitDown.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleSitDown.h
Labels: tested

#380 `CTaskSimpleClearLookAt`
  source/game_sa/Tasks/TaskTypes/TaskSimpleClearLookAt.h
Labels: tested

#379 `CTaskSimpleCower `
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCower.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCower.h
Labels: tested

#393 `CTaskSimpleFightingControl`
  source/InjectHooksMain.cpp
  source/game_sa/Core/Vector.cpp
  source/game_sa/Core/Vector.h
  source/game_sa/Events/EntityCollisionEvents.cpp
  source/game_sa/Events/EntityCollisionEvents.h
  source/game_sa/Events/EventPotentialWalkIntoBuilding.cpp
  source/game_sa/Events/EventVehicleCollision.cpp
  source/game_sa/Events/EventVehicleCollision.h
  source/game_sa/PedGeometryAnalyser.cpp
  source/game_sa/PedGeometryAnalyser.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleFightingControl.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleFightingControl.h
Labels: tested

#416 Ped Debug / Tasks viewer
  source/game_sa/Enums/eTaskType.h
  source/game_sa/Tasks/TaskManager.cpp
  source/game_sa/Tasks/TaskManager.h
  source/game_sa/Tasks/TaskTypes/TaskComplexBeInGroup.cpp
  source/game_sa/World.cpp
  source/game_sa/common.cpp
  source/toolsmenu/CDebugMenu.cpp
  source/toolsmenu/DebugModules/DebugModules.cpp
  source/toolsmenu/DebugModules/DebugModules.h
  source/toolsmenu/DebugModules/Ped/PedDebugModule.cpp
  source/toolsmenu/DebugModules/Ped/PedDebugModule.h
  source/toolsmenu/DebugModules/Ped/PedSpawnerModule.cpp
  source/toolsmenu/DebugModules/Ped/PedSpawnerModule.h
Labels: enhancement, tested

#420 `TaskSimplePickUpBike`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimplePickUpBike.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimplePickUpBike.h
Labels: tested

#389 `CTaskSimpleCarAlign`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarAlign.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarAlign.h
  source/game_sa/VehicleAnimGroupData.cpp
Labels: tested

#426 `CTaskSimpleShakeFist`
  source/InjectHooksMain.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleShakeFist.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleShakeFist.h
Labels: tested
