Repository gta-reversed/gta-reversed, pull requests merged in 2025-03, with the labels that each got.

#884 `COcclusion` and related fixes, refactors + Reverse `ProcessBeforeRendering`
  source/extensions/FixedVector.hpp
  source/game_sa/ActiveOccluder.cpp
  source/game_sa/ActiveOccluder.h
  source/game_sa/Entity/Entity.cpp
  source/game_sa/Entity/Entity.h
  source/game_sa/FileLoader.cpp
  source/game_sa/Occluder.cpp
  source/game_sa/Occluder.h
  source/game_sa/Occlusion.cpp
  source/game_sa/Occlusion.h
  source/game_sa/Tasks/TaskTypes/TaskComplexUseSwatRope.cpp
  source/game_sa/common.cpp
  source/game_sa/common.h
  source/toolsmenu/DebugModules/COcclusionDebugModule.cpp
  source/toolsmenu/DebugModules/CTeleportDebugModule.cpp
Labels: tested

#921 Wrap script commands into anonymous namespaces (Hide functions from the linker)
  source/game_sa/Scripts/Commands/Basic.cpp
  source/game_sa/Scripts/Commands/Camera.cpp
  source/game_sa/Scripts/Commands/Character.cpp
  source/game_sa/Scripts/Commands/Clock.cpp
  source/game_sa/Scripts/Commands/Comparasion.cpp
  source/game_sa/Scripts/Commands/Game.cpp
  source/game_sa/Scripts/Commands/Generic.cpp
  source/game_sa/Scripts/Commands/Math.cpp
  source/game_sa/Scripts/Commands/Mission.cpp
  source/game_sa/Scripts/Commands/Object.cpp
  source/game_sa/Scripts/Commands/Pad.cpp
  source/game_sa/Scripts/Commands/Ped.cpp
  source/game_sa/Scripts/Commands/Player.cpp
  source/game_sa/Scripts/Commands/Script.cpp
  source/game_sa/Scripts/Commands/Sequence.cpp
  source/game_sa/Scripts/Commands/Text.cpp
  source/game_sa/Scripts/Commands/Unused.cpp
  source/game_sa/Scripts/Commands/Utility.cpp
  source/game_sa/Scripts/Commands/Vehicle.cpp
Labels: tested

#873 Finish up and refactor `CTaskSimpleClimb`
  source/game_sa/Entity/Physical.cpp
  source/game_sa/Events/EventHandler.cpp
  source/game_sa/Events/EventSoundQuiet.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexJump.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleInAir.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleInAir.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleJump.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleJump.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSwim.h
Labels: tested

#871 Finish and fix `CTaskComplexDestroyCarMelee`
  source/game_sa/Core/Vector2D.h
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarMelee.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDestroyCarMelee.h
  source/game_sa/Tasks/TaskTypes/TaskComplexJump.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleInAir.cpp
  source/toolsmenu/UIRenderer.cpp
Labels: tested

#951 CBmx improvements, [Tested]
  source/game_sa/Entity/Vehicle/Bmx.cpp
  source/game_sa/Entity/Vehicle/QuadBike.cpp
  source/game_sa/RideAnimData.h
Labels: tested

#959 CPed::RemoveWeaponWhenEnteringVehicle and PreRenderAfterTest
  source/game_sa/Entity/Ped/Ped.cpp
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/PedClothesDesc.cpp
  source/game_sa/PedClothesDesc.h
  source/game_sa/WeaponInfo.h
Labels: tested

#956 Stat script commands
  source/game_sa/Scripts/Commands/Commands.hpp
  source/game_sa/Scripts/Commands/Game.cpp
  source/game_sa/Scripts/Commands/Stat.cpp
  source/game_sa/Scripts/RunningScript.cpp
Labels: tested

#823 Update README.md
  README.md
Labels: tested

#672 `CTaskComplexEnterCarAsPassengerTimed`
  source/InjectHooksMain.cpp
  source/extensions/EntityRef.hpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.h
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCarAsPassengerTimed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCarAsPassengerTimed.h
  source/toolsmenu/UIRenderer.cpp
Labels: untested

#958 Zone script commands
  source/game_sa/GangWars.cpp
  source/game_sa/PopCycle.cpp
  source/game_sa/PopCycle.h
  source/game_sa/Radar.cpp
  source/game_sa/Scripts/Commands/Commands.hpp
  source/game_sa/Scripts/Commands/Zone.cpp
  source/game_sa/Scripts/RunningScript.cpp
  source/game_sa/Streaming.cpp
  source/game_sa/TheZones.cpp
  source/game_sa/TheZones.h
  source/game_sa/Zone.h
  source/game_sa/ZoneInfo.h
Labels: tested

#963 Rename `CVehicle`/`CPhysical` fields
  source/game_sa/Audio/entities/AEVehicleAudioEntity.cpp
  source/game_sa/Camera.cpp
  source/game_sa/CarEnterExit.cpp
  source/game_sa/Entity/Entity.cpp
  source/game_sa/Entity/Object/CutsceneObject.cpp
  source/game_sa/Entity/Object/Object.cpp
  source/game_sa/Entity/Ped/Ped.cpp
  source/game_sa/Entity/Physical.cpp
  source/game_sa/Entity/Physical.h
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Boat.cpp
  source/game_sa/Entity/Vehicle/Plane.cpp
  source/game_sa/Entity/Vehicle/Trailer.cpp
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Events/EventHandler.cpp
  source/game_sa/Events/EventPotentialWalkIntoVehicle.cpp
  source/game_sa/Events/EventVehicleCollision.cpp
  source/game_sa/Fire.cpp
  source/game_sa/GameLogic.cpp
  source/game_sa/InterestingEvents.cpp
  source/game_sa/Pickup.cpp
  source/game_sa/Renderer.cpp
  source/game_sa/VehicleRecording.cpp
  source/game_sa/World.cpp
Labels: tested

#962 Rename mission id enums
  source/game_sa/AutoPilot.h
  source/game_sa/CarAI.cpp
  source/game_sa/CarCtrl.cpp
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Boat.cpp
  source/game_sa/Entity/Vehicle/Plane.cpp
  source/game_sa/Enums/eCarMission.h
  source/game_sa/Scripts/TheScripts.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDriveMission.h
  source/game_sa/Tasks/TaskTypes/TaskComplexCopInCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexUseSwatRope.cpp
  source/game_sa/VehicleRecording.cpp
  source/game_sa/World.cpp
Labels: tested

#955 Script camera commands
  contrib/scripts-hooks-gen.py
  source/game_sa/Camera.cpp
  source/game_sa/Camera.h
  source/game_sa/Scripts/Commands/Camera.cpp
  source/game_sa/Scripts/TheScripts.cpp
  source/game_sa/Scripts/TheScripts.h
Labels: untested

#674 `CTaskSimpleKillPedWithCar`
  source/InjectHooksMain.cpp
  source/game_sa/Audio/entities/AEVehicleAudioEntity.cpp
  source/game_sa/Audio/entities/AEVehicleAudioEntity.h
  source/game_sa/Entity/Physical.cpp
  source/game_sa/Entity/Physical.h
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Vehicle.h
  source/game_sa/Tasks/TaskSimple.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleKillPedWithCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleKillPedWithCar.h
Labels: tested

#574 Reverse parts of `CustomBuildingDNPipeline`
  source/game_sa/Cover.cpp
  source/game_sa/Pipelines/CustomBuilding/CustomBuildingDNPipeline.cpp
  source/game_sa/Pipelines/CustomBuilding/CustomBuildingDNPipeline.h
  source/game_sa/RenderWare/rw/rwcore.h
  source/game_sa/common.h
Labels: tested

#950 Script text related commands
  source/game_sa/Font.h
  source/game_sa/Hud.cpp
  source/game_sa/Scripts/Commands/Basic.cpp
  source/game_sa/Scripts/Commands/Game.cpp
  source/game_sa/Scripts/Commands/Text.cpp
  source/game_sa/Scripts/RunningScript.cpp
  source/game_sa/Scripts/RunningScript.h
  source/game_sa/Scripts/TheScripts.h
  source/reversiblehooks/ReversibleHooks.cpp
Labels: tested

#482 Curvy Cruves
  source/InjectHooksMain.cpp
  source/game_sa/Core/Vector2D.h
  source/game_sa/Curves.cpp
  source/game_sa/Curves.h
  source/toolsmenu/UIRenderer.cpp
Labels: tested

#556 `CTaskComplexAvoidPedWhileWandering`
  source/game_sa/Collision/ColSphere.cpp
  source/game_sa/Collision/ColSphere.h
  source/game_sa/Events/EventPedCollisionWithPed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexAvoidEntity.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexAvoidOtherPedWhileWandering.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexAvoidOtherPedWhileWandering.h
  source/game_sa/Tasks/TaskTypes/TaskComplexGangFollower.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexGangFollower.h
  source/game_sa/Timer.h
Labels: tested, to be merged

#653 `CTaskComplexPolicePursuit`
  source/game_sa/Entity/Ped/Ped.h
  source/game_sa/Tasks/TaskTypes/TaskComplexCopInCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexPolicePursuit.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexPolicePursuit.h
Labels: tested

#810 Bugs debug tool v1
  source/game_sa/Animation/AnimBlendSequence.cpp
  source/game_sa/Audio/AESound.cpp
  source/game_sa/Coronas.cpp
  source/reversiblebugfixes/Bugs.hpp
  source/reversiblebugfixes/ReversibleBugFix.hpp
  source/toolsmenu/DebugModules/BugsDebugModule.cpp
  source/toolsmenu/DebugModules/BugsDebugModule.hpp
  source/toolsmenu/DebugModules/DebugModules.cpp
Labels: tested

#621 CCover
  source/Base.h
  source/InjectHooksMain.cpp
  source/StdInc.h
  source/extensions/EntityRef.hpp
  source/game_sa/Attractors/PedAttractor.h
  source/game_sa/Audio/entities/AEPedlessSpeechAudioEntity.h
  source/game_sa/Collision/Box.cpp
  source/game_sa/Core/PtrListDoubleLink.cpp
  source/game_sa/Core/PtrListDoubleLink.h
  source/game_sa/Cover.cpp
  source/game_sa/Cover.h
  source/game_sa/CoverPoint.cpp
  source/game_sa/CoverPoint.h
  source/game_sa/Entity/Entity.h
  source/game_sa/Events/GroupEventHandler.h
  source/game_sa/Formation.cpp
  source/game_sa/Formation.h
  source/game_sa/IKChain_c.h
  source/game_sa/Occluder.h
  source/game_sa/Plugins/TwoDEffectPlugin/2dEffect.h
  source/game_sa/PointList.cpp
  source/game_sa/PointList.h
  source/game_sa/RGBA.h
  source/game_sa/Route.hpp
  source/game_sa/Scripts/TheScripts.h
  source/game_sa/Tasks/TaskTypes/TaskComplexKillPedOnFootArmed.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleIKChain.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleUseGun.h
  source/game_sa/World.cpp
  source/toolsmenu/DebugModules/CoverPointsDebugModule.cpp
  source/toolsmenu/DebugModules/CoverPointsDebugModule.hpp
  source/toolsmenu/DebugModules/DebugModule.h
  source/toolsmenu/DebugModules/DebugModules.cpp
  source/toolsmenu/DebugModules/TwoDEffectsDebugModule.cpp
Labels: tested

#657 Reverse CarAI
  source/InjectHooksMain.cpp
  source/game_sa/AutoPilot.cpp
  source/game_sa/AutoPilot.h
  source/game_sa/CarAI.cpp
  source/game_sa/CarAI.h
  source/game_sa/CarCtrl.cpp
  source/game_sa/CarCtrl.h
  source/game_sa/CarGenerator.cpp
  source/game_sa/Core/Rect.h
  source/game_sa/Core/Vector.cpp
  source/game_sa/Core/Vector.h
  source/game_sa/Core/Vector2D.cpp
  source/game_sa/Core/Vector2D.h
  source/game_sa/Entity/Object/Object.cpp
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Bike.cpp
  source/game_sa/Entity/Vehicle/Plane.cpp
  source/game_sa/Entity/Vehicle/Train.cpp
  source/game_sa/Entity/Vehicle/Vehicle.cpp
  source/game_sa/PathFind.cpp
  source/game_sa/SetPiece.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.h
  source/game_sa/Tasks/TaskTypes/TaskComplexCarDriveMission.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCopInCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexCopInCar.h
  source/game_sa/Tasks/TaskTypes/TaskComplexDieInCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDriveToPoint.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexDriveWander.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexKillCriminal.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexKillPedFromBoat.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexKillPedFromBoat.h
  source/game_sa/Tasks/TaskTypes/TaskComplexKillPedOnFootArmed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexMedicTreatInjuredPed.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexRoadRage.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexStealCar.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarDrive.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetTempAction.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetTempAction.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitToSlowDown.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleGangDriveBy.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleGangDriveBy.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleSetPedAsAutoDriver.cpp
  source/game_sa/VehicleRecording.cpp
  source/game_sa/World.cpp
Labels: tested

#451 `CTaskComplexShuffleSeats`
  source/InjectHooksMain.cpp
  source/game_sa/Core/PtrNodeDoubleLink.h
  source/game_sa/Cover.cpp
  source/game_sa/Enums/eTargetDoor.h
  source/game_sa/Events/EventHandler.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexShuffleSeats.cpp
  source/game_sa/Tasks/TaskTypes/TaskComplexShuffleSeats.h
  source/game_sa/Tasks/TaskTypes/TaskSimpleAnim.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarGoToPointNearDoorUntilDoorNotInUse.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarShuffle.cpp
  source/game_sa/Tasks/TaskTypes/TaskSimpleCarShuffle.h
  source/toolsmenu/DebugModules/Spawner/PedSpawner.cpp
  source/toolsmenu/DebugModules/Spawner/PedSpawner.h
Labels: tested

#952 Add more assert/verify to scripts stuff
  source/Base.h
  source/CMakeLists.txt
  source/app/app_debug.h
  source/extensions/ScriptCommands.cpp
  source/extensions/ScriptCommands.h
  source/game_sa/Audio/AudioZones.cpp
  source/game_sa/Audio/AudioZones.h
  source/game_sa/Camera.cpp
  source/game_sa/Collision/ColModel.cpp
  source/game_sa/Collision/ColModel.h
  source/game_sa/Core/Rect.h
  source/game_sa/DecisionMakerTypes.h
  source/game_sa/Enums/eScriptCommands.h
  source/game_sa/Scripts/CommandParser/Parser.hpp
  source/game_sa/Scripts/CommandParser/ReadArg.hpp
  source/game_sa/Scripts/CommandParser/StoreArg.hpp
  source/game_sa/Scripts/Commands/Basic.cpp
  source/game_sa/Scripts/Commands/CLEO/Memory.cpp
  source/game_sa/Scripts/Commands/CLEO/World.cpp
  source/game_sa/Scripts/Commands/Camera.cpp
  source/game_sa/Scripts/Commands/Character.cpp
  source/game_sa/Scripts/Commands/Mission.cpp
  source/game_sa/Scripts/Commands/Object.cpp
  source/game_sa/Scripts/RunningScript.cpp
  source/game_sa/Scripts/RunningScript.h
  source/game_sa/Scripts/ScriptParam.h
  source/game_sa/Scripts/TheScripts.cpp
  source/game_sa/Scripts/TheScripts.h
  source/game_sa/Shadows.cpp
  source/game_sa/Sprite2d.cpp
  source/reversiblehooks/ReversibleHook/ScriptCommand.h
  source/reversiblehooks/ReversibleHooks.cpp
  source/toolsmenu/DebugModules/Script/MissionDebugModule.cpp
  source/toolsmenu/UIRenderer.cpp
Labels: tested

#728 `C3DMarkers::PlaceMarker`
  source/game_sa/3dMarker.cpp
  source/game_sa/3dMarker.h
  source/game_sa/3dMarkers.cpp
  source/game_sa/3dMarkers.h
  source/game_sa/Checkpoint.cpp
  source/game_sa/Core/PtrListDoubleLink.cpp
Labels: tested

#981 Zero init `CAutomobile::m_apWheelCollisionEntity`
  source/game_sa/Entity/Vehicle/Automobile.cpp
  source/game_sa/Entity/Vehicle/Automobile.h
Labels: tested

#980 Fix seemingly out-of-bounds read of `m_LocalVars` in `CRunningScript`
  source/game_sa/Scripts/RunningScript.h
  source/game_sa/Scripts/TheScripts.cpp
Labels: tested

#983 Fix climbing
  source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp
Labels: tested
